<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="SEGOTW10383333" name="com.fayaaz.ali.Integration.UserManagerITTest" tests="4" failures="0" timestamp="2019-09-09T15:21:32 CEST" time="0.031" errors="1">
  <testcase name="shouldReturnListOfAllUsersWhenGetAllUsersCalled" time="0.000" classname="com.fayaaz.ali.Integration.UserManagerITTest">
    <skipped/>
  </testcase> <!-- shouldReturnListOfAllUsersWhenGetAllUsersCalled -->
  <testcase name="SetUpClass" time="0.031" classname="com.fayaaz.ali.Integration.UserManagerITTest">
    <error type="java.sql.SQLException" message="No suitable driver found for jdbc:h2:mem:test">
      <![CDATA[java.sql.SQLException: No suitable driver found for jdbc:h2:mem:test
at java.sql.DriverManager.getConnection(DriverManager.java:689)
at java.sql.DriverManager.getConnection(DriverManager.java:270)
at com.fayaaz.ali.services.BaseTest.getH2Connection(BaseTest.java:35)
at com.fayaaz.ali.Integration.UserManagerITTest.SetUpClass(UserManagerITTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </error>
  </testcase> <!-- SetUpClass -->
  <testcase name="shouldReturnTrue" time="0.000" classname="com.fayaaz.ali.Integration.UserManagerITTest">
    <skipped/>
  </testcase> <!-- shouldReturnTrue -->
  <testcase name="shouldReturnAnInstanceofUserManager" time="0.000" classname="com.fayaaz.ali.Integration.UserManagerITTest">
    <skipped/>
  </testcase> <!-- shouldReturnAnInstanceofUserManager -->
</testsuite> <!-- com.fayaaz.ali.Integration.UserManagerITTest -->
